stages:
  - build
  - test
  - deploy

#variables:


before_script:
  - python -m venv venv
  - source \apiPython\Scripts\activate.bat
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python app.py

#test:
#  stage: test
#  script:
#    - pytest
#
#deploy:
#  stage: deploy
#  script:
#    - # Adicione comandos de implantação, se necessário
#  only:
#    - master  # Implante apenas em commits na branch master
